import subprocess
import sys
import tempfile
import os

class SandboxExecutor:
    """
    Environment-in-the-Loop sandbox executor.
    Runs the Python code securely, mocking external dependencies and returning structured traces.
    """
    
    def __init__(self, timeout_seconds=10):
        self.timeout_seconds = timeout_seconds

    def execute(self, code_string, mock_inputs=None):
        """
        Executes the provided Python code string in an isolated subprocess.
        :param code_string: Python code generated by the Translation Expert.
        :param mock_inputs: Dictionary of environment variables or mocked inputs to pass to the script.
        :return: dict containing stdout, stderr, return_code, error_type
        """
        # Set up environment variables representing the mocked COBOL data/inputs
        env = os.environ.copy()
        if mock_inputs:
            for key, val in mock_inputs.items():
                env[key] = str(val)

        # Write code to a temporary file to run
        with tempfile.NamedTemporaryFile(mode='w', suffix='.py', delete=False) as temp_file:
            temp_file.write(code_string)
            temp_file_path = temp_file.name

        result = {
            "stdout": "",
            "stderr": "",
            "return_code": 0,
            "error_type": None,
            "timeout": False
        }

        try:
            # Execute the python file securely
            process = subprocess.run(
                [sys.executable, temp_file_path],
                capture_output=True,
                text=True,
                timeout=self.timeout_seconds,
                env=env
            )
            result["stdout"] = process.stdout
            result["stderr"] = process.stderr
            result["return_code"] = process.returncode
            if process.returncode != 0:
                result["error_type"] = "RuntimeError"

        except subprocess.TimeoutExpired as e:
            result["timeout"] = True
            result["error_type"] = "TimeoutError"
            result["stdout"] = e.stdout.decode('utf-8') if e.stdout else ""
            result["stderr"] = e.stderr.decode('utf-8') if e.stderr else f"Execution timed out after {self.timeout_seconds}s"
        except Exception as e:
            result["error_type"] = "SystemError"
            result["stderr"] = str(e)
            result["return_code"] = -1
        finally:
            # Clean up temp file
            if os.path.exists(temp_file_path):
                os.remove(temp_file_path)

        return result
